name: Christiansen Photography
favicon: null
layout_spectrum: 0.16742250067181885
typography_spectrum: 0.7081023135688156
title: Christiansen Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfb'
    - '#4c7690'
    - '#8d8a7c'
    - '#263e4b'
    - '#a7bcc4'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
