name: Christiansen Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Christiansen Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#acbfc6'
    - '#7f939b'
    - '#484d39'
    - '#436074'
    - '#2d3228'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
